language: java
jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2"

before_install:
  - openssl aes-256-cbc -K $encrypted_44c02787e156_key -iv $encrypted_44c02787e156_iv -in settings.xml.enc -out settings.xml -d
  - cp ./settings.xml ~/.m2/settings.xml

script: mvn verify

deploy:
  provider: script
  script: mvn deploy --quiet
  on:
    tags: true