language: java
jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm-cache"

before_install:
  - npm config set cache "$HOME/.npm-cache"
  - openssl aes-256-cbc -K $encrypted_44c02787e156_key -iv $encrypted_44c02787e156_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv settings.xml $HOME/.m2/settings.xml
  - mv .npmrc $HOME/.npmrc

script:
  - mvn verify
  - git status

deploy:

  # deploy npm
  - provider: script
    skip_cleanup: true
    script: node_modules/.bin/lerna publish from-package --yes --no-verify-access
    on:
      tags: true

  # deploy maven
  - provider: script
    skip_cleanup: true
    script: mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true
    on:
      tags: true