language: java
jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm-cache"

before_install:
  - npm config set cache "$HOME/.npm-cache"
  - openssl aes-256-cbc -K $encrypted_44c02787e156_key -iv $encrypted_44c02787e156_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - mv settings.xml $HOME/.m2/settings.xml
  - mv .npmrc $HOME/.npmrc
script: mvn verify --quiet -B

deploy:

  # deploy maven
  - provider: script
    script: mvn deploy -DskipTests=true -Dmaven.javadoc.skip=true --quiet
    on:
      tags: true

  # deploy npm
  - provider: script
    script: npm run lerna -- publish from-package
    on:
      tags: true