version: '3'
services:
  front-end:
    build:
      context: ./frontend/
      dockerfile: Dockerfile-run
    ports: 
      - "3000:8080"
    volumes:
      - "./frontend/:/app"
  # back-end:
  #   build:
  #     context: ./backend/
  #     dockerfile: Dockerfile-run
  #   ports:
  #     - "3001:8080"
  #   volumes:
  #     - "./backend/:/app"
  data-base:
    image: cassandra:3
    ports:
      - "9042:9042"
