# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Flock. eco build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file ./pom.xml
    - uses: actions/upload-artifact@v2
      with:
        name: maven-jars
        path: ./**/target/*.jar

  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run bootstrap

  publish-maven:
    runs-on: ubuntu-latest
    needs: build-maven
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/download-artifact@v2
        with:
          name: maven-jars
      - name: Publish maven to github packages
        run: mvn jar:jar deploy:deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-react:
    runs-on: ubuntu-latest
    needs: build-react
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Publish react to github packages
        run: |
          npm install
          npm config set @flock-community:registry https://npm.pkg.github.com/flock-community/
          npm config set //npm.pkg.github.com/flock-community/:_authToken=$NODE_AUTH_TOKEN
          npm config list
          npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

