name: Flock. eco publish

on:
  create:
    tags:
      - v*

jobs:

  publish-kotlin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: jfrog-flock-community
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
      - name: Publish maven to github packages
        run: mvn -B deploy -DskipTests=true --file ./pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.JFROG_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.JFROG_MAVEN_PASSWORD }}

  publish-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Publish react to github packages
        run: |
          npm install
          npm run bootstrap
          npm run generate
          npm run compile
          npm run build
          npm run prettier
          npm config set @flock-community:registry https://flock.jfrog.io/artifactory/api/npm/flock-npm/
          npm config set //flock.jfrog.io/artifactory/api/npm/flock-npm/:_authToken=$NODE_AUTH_TOKEN
          npm config set //flock.jfrog.io/artifactory/api/npm/flock-npm/:username=$NODE_USERNAME
          npm config set //flock.jfrog.io/artifactory/api/npm/flock-npm/:email=$NODE_EMAIL
          npm config set //flock.jfrog.io/artifactory/api/npm/flock-npm/:always-auth=true
          npm run publish
        env:
          NODE_USERNAME: ${{secrets.JFROG_USERNAME}}
          NODE_EMAIL: ${{secrets.JFROG_USERNAME}}
          NODE_AUTH_TOKEN: ${{secrets.JFROG_NODE_TOKEN}}
